### PR TITLE
Develop

### PR DESCRIPTION
**Pull request by ismeleft**
老師午安，我是陳玟穎

準備提交給老師本週作業的測試連結

[](http://52.192.139.251:3000/api/mrts)

[](http://52.192.139.251:3000/api/attraction/10)

[](http://52.192.139.251:3000/api/attractions?page=1)

[](http://52.192.139.251:3000/api/attractions?page=0&keyword=%E5%8C%97%E6%8A%95)

### CODE REVIEW

**Comment by cwpeng** [comment]
Leave your testing URLs so that I can test for you.

**Comment by ismeleft** [comment]
連結如下：
[](http://52.192.139.251:3000/api/mrts)

[](http://52.192.139.251:3000/api/attraction/10)

[](http://52.192.139.251:3000/api/attractions?page=1)

[](http://52.192.139.251:3000/api/attractions?page=0&keyword=%E5%8C%97%E6%8A%95)

**Comment by ismeleft** [comment]
原來用了內建的連結，訊息會被吃掉😅
連結如下：
http://52.192.139.251:3000/api/mrts

http://52.192.139.251:3000/api/attraction/10

http://52.192.139.251:3000/api/attractions?page=1

http://52.192.139.251:3000/api/attractions?page=0&keyword=%E5%8C%97%E6%8A%95

**Review by cwpeng — CHANGES_REQUESTED** [review]
1. Always use second parameter of execute method to integrate variables into SQL query to avoid SQL injection.
2. Use keyword to search only mrt and attraction name.

Fix issues and re-request review.

**Comment by ismeleft** [comment]
老師晚安， 我已進行程式碼修改，再請您過目，謝謝！

**Review by cwpeng — APPROVED** [review]
OK. Done.

**Pull request merged**
